# Generated by Django 3.2.6 on 2021-10-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(decimal_places=100, max_digits=100)),
                ('recall', models.DecimalField(decimal_places=100, max_digits=100)),
                ('accurancy', models.DecimalField(decimal_places=100, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Web.output')),
            ],
        ),
    ]
