# Generated by Django 3.2.6 on 2021-10-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.output'),
        ),
        migrations.AlterField(
            model_name='output',
            name='accurancy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='output',
            name='precision',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='output',
            name='recall',
            field=models.FloatField(),
        ),
    ]
